name: parolemobile
description: Open source password generator from Shivam Yadav

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  clipboard: ^0.1.3
  flutter_vector_icons: ^1.0.0
  fluttertoast: ^8.0.8
  google_fonts: ^2.1.0
  secure_random: ^1.0.1
  share_plus: ^2.1.4
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
